---
- name: Ensure that packages required for RDP are installed
  become: yes
  apt:
    state: present
    name:
      - xrdp

# ensure that xrdp starts every RDP session using xfce
# https://askubuntu.com/questions/135483/how-to-configure-xrdp-to-start-cinnamon-as-default-desktop-session
- name: Ensure that .xsession file exists in home directory with correct contents
  copy:
    src: .xsession
    dest: ~/.xsession

- name: Ensure that the .xsession file has the correct permissions
  file:
    path: ~/.xsession
    mode: u=rwx,go-rwx
  notify: ["Restart the xrdp service"]