---
- name: Ensure that the XFCE base packages are installed
  become: true
  apt:
    state: present
    name:
      - xserver-xorg
      - xfonts-base
      - xubuntu-desktop
      - lightdm

# switching the default display manager
# https://techpiezo.com/linux/switch-display-manager-in-ubuntu-20-04/
- name: Check current status of the default display manager file
  stat:
    path: /etc/X11/default-display-manager
    checksum_algorithm: sha256
  register: x11_display_manager

- name: Ensure that lightdm is the default display manager
  become: true
  script: change-default-display-manager.sh lightdm
  when:
    x11_display_manager.stat.checksum != 'ce87bfbb15be1bba4d16d93c1a3a8b0184737204f40afc92a078bc6aed4b7094'

- name: Restart the display-manager service
  become: true
  service:
    name: display-manager
    state: restarted
  when:
    x11_display_manager.stat.checksum != 'ce87bfbb15be1bba4d16d93c1a3a8b0184737204f40afc92a078bc6aed4b7094'
